New ride flow
cornell-dti/carriage-rider pull request #57
Opened 2021-03-21 02:50 UTC by tyang98

### Summary 

This pull request is implements the new designs for the ride flow. Users are able to now choose their locations, choose what days a ride can be repeated, and send the information to the backend. This pull request will likely be over the 1000 diff limit, but I believe there is no way to split up this PR without each component of the ride flow being connected to each other. Thus, this PR will not be merged **until we thoroughly test through everything.** 

- [x] implemented new Rider design
- [x] added recurring ride selection to ride flow
- [x] Create ride from the frontend and send to the backend.  
- [x] Filter custom locations 

### Test Plan 

I tested the ride flow through an emulator and with Postman.

### Screenshots 

<img width="300" alt="Screen Shot 2021-03-20 at 10 37 37 PM" src="https://user-images.githubusercontent.com/17262023/111892032-f3695680-89cd-11eb-82af-dc3eb21dfa81.png">
<img width="298" alt="Screen Shot 2021-03-20 at 10 37 45 PM" src="https://user-images.githubusercontent.com/17262023/111892034-f5331a00-89cd-11eb-9933-61c3aaadaa2c.png">
<img width="302" alt="Screen Shot 2021-03-20 at 10 38 01 PM" src="https://user-images.githubusercontent.com/17262023/111892036-f7957400-89cd-11eb-8b09-c0dfa115d441.png">
<img width="307" alt="Screen Shot 2021-03-20 at 10 38 31 PM" src="https://user-images.githubusercontent.com/17262023/111892037-f9f7ce00-89cd-11eb-9a60-a95f3d112e08.png">
<img width="300" alt="Screen Shot 2021-03-20 at 10 38 38 PM" src="https://user-images.githubusercontent.com/17262023/111892038-fbc19180-89cd-11eb-9950-e73b6511cc5c.png">

### Notes 

-  Variation on the location displaying design
- No integration of maps

2021-03-21 12:47 UTC, mg2239 commented
Is it possible to split up this PR by screen? So we have a PR for each screen (but no ride flow), then the last PR implements the flow for testing?

2021-03-29 05:30 UTC, helenxuyang reviewed
Overall really good progress, this is a TON of work!! Has a few style issues especially with the buttons, clunky behavior related to text fields, and a bug in locations when creating a second ride. Left some questions in the code as well. 

Here's a screen recording of me messing around with the flow, issues I identified are listed below. 
https://user-images.githubusercontent.com/60579411/112789683-a4559e00-902b-11eb-8e2e-8ee42b11df78.mp4

Visual 
- back button icon isn't centered and button is cut off on the bottom on some pages, next button overflows -> unsure of the problem here, but the widget trees for the buttons seem really complicated right now and could probably be simplified?
- on the date/time selection, the end date and drop-off time don't seem to be in line vertically -> probably need a GridView 
- on the review page, the end date and drop-off time don't seem to be in line vertically -> probably need a GridView
- text field decorations seem to flash on and off on taps, not sure what's going on here

Issues with text/keyboard
- tapping the text inputs causes the keyboard to come into view for a split second before the next page comes up -> this might get fixed automatically if we simplify the flow anyway
- due to the keyboard coming up, only one row of the autofill for locations is visible -> there is some way in Flutter to have everything shift up when the keyboard opens so that you have space, I think it's a Scaffold property? 
- the keyboard remains open after navigating back from the select location dates, and doesn't seem to be closeable so you have to just use the next button on the keyboard until you get to the end -> again, might get fixed automatically if we simplify the flow 
- the keyboard remains open after selecting dates/times and allows the user to type in these fields which shouldn't be allowed -> since the user should pretty much just use these as buttons, maybe surround with an IgnorePointer and then GestureDetector to use onTap to open the next page

Issues when creating a second ride
- locations seem to be carrying over -> clear when the flow is complete
- probably related to the location issue, the set location button doesn't appear even when there are rides in both fields

Other changes:
The locations should be changed so that the provider just fetches locations once when the app first starts and saves this into a variable that all the pages can access rather than fetching every time, which shows the loading symbol and makes unnecessary requests

Not approving yet especially if this PR will get split into multiple PRs anyway, and will want to review it again in more detail to make sure I'm not missing anything else

2021-03-29 06:59 UTC, tyang98 commented on lib/pages/ride-flow/FlowWidgets.dart
> +      {Key key, this.page, this.text, this.repeatPage, this.onPressed})
I think I initially wanted to do something with repeating a particular page in the flow.

2021-03-29 07:28 UTC, tyang98 commented on lib/pages/ride-flow/FlowWidgets.dart
> +            transform: Matrix4.translationValues(0.0, -15.0, 0.0),
Yeah it shifts the icon 15 pixels up. Without it, the distance between the icon and the upper bar is quite distant.

2021-03-29 07:53 UTC, tyang98 commented on lib/pages/ride-flow/Request_Ride_Loc.dart
> +class LocationInput extends StatefulWidget {
Yes I agree, this should be a stateless widget

2021-03-29 08:05 UTC, tyang98 commented on lib/pages/ride-flow/Review_Ride.dart
> +                    widget.ride.recurringDays != null
Not sure, the designs do not provide an instance of this case

2021-04-06 01:06 UTC, helenxuyang commented on lib/models/Location.dart
>  //Converts a list of locations [locations] to a Map containing location ids (key) to locations (value).
I know this wasn't changed here, but the locationsById function should probably be moved into LocationsProvider?

2021-04-06 01:11 UTC, helenxuyang commented on lib/pages/ride-flow/FlowWidgets.dart
> +                    minWidth: MediaQuery.of(context).size.width * 0.1,
Button still looks a bit wide and the arrow isn't centered on my device, so I'm not sure if minWidth is the best thing to use here

2021-04-06 06:06 UTC, tyang98 commented on lib/models/Location.dart
> +  Map<String, dynamic> toJson() =>
Oh i don't think it is necessary anymore. Beforehand, I was trying to send an entire location object to the backend.

2021-04-12 23:21 UTC, helenxuyang requested changes
Overall looking functional as a whole! I will update locations in a new PR because there's already so much going on here. Not approving yet because of the line that needs to be added for each TextFormField and the design stuff for the review ride (awkward for non-recurring rides) + ride confirmation (adding the button back) pages, but will approve after those. Awesome work Tony!!

2021-04-12 23:21 UTC, helenxuyang commented on lib/providers/RidesProvider.dart
> +      'rider': riderProvider.info,
riderProvider.info.id

2021-04-12 23:27 UTC, tyang98 commented on lib/pages/ride-flow/Request_Ride_Time.dart
> +      focusNode: AlwaysDisabledFocusNode(),
done

2021-04-12 23:27 UTC, tyang98 commented on lib/pages/ride-flow/Request_Ride_Time.dart
> +      decoration: InputDecoration(
done

2021-04-12 23:28 UTC, tyang98 commented on lib/pages/ride-flow/Request_Ride_Time.dart
> +                      focusNode: AlwaysDisabledFocusNode(),
done

2021-04-12 23:28 UTC, tyang98 commented on lib/pages/ride-flow/Request_Ride_Time.dart
> +          focusNode: AlwaysDisabledFocusNode(),
done

2021-04-12 23:28 UTC, tyang98 commented on lib/pages/ride-flow/Request_Ride_Time.dart
> +                            focusNode: AlwaysDisabledFocusNode(),
done

2021-04-12 23:28 UTC, tyang98 commented on lib/pages/ride-flow/Request_Ride_Time.dart
> +                            focusNode: AlwaysDisabledFocusNode(),
done

2021-04-12 23:29 UTC, tyang98 commented on lib/pages/ride-flow/Request_Ride_Time.dart
> +                                          .difference(DateFormat('MM/dd/yyyy')
thanks for the tip! fixed

2021-04-12 23:45 UTC, tyang98 commented on lib/pages/ride-flow/Review_Ride.dart
> +                              widget.ride.endDate != null
I agree, will remove

2021-04-13 06:29 UTC, helenxuyang approved these changes

2021-04-13 06:31 UTC, merged

2021-05-06 00:06 UTC, tyang98 commented on lib/pages/ride-flow/FlowWidgets.dart
> +    return Expanded(
I was having issues with positioning the widget

2021-05-06 00:06 UTC, tyang98 commented on lib/pages/ride-flow/ToggleButton.dart
> +    setState(() {
I think setState is necessary